language: python

os:
  - linux

python:
  - "2.7"
  - "3.9"
  - "3.10"

install:
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - nosetests --with-doctest triangle/tri.py

notifications:
  email: false
